source 'https://rubygems.org'

# Test gems we use that require system libraries.

# libmysql
gem 'mysql2'
# libxml2, libxslt
gem 'nokogiri', '>= 1.10.8'
# libsqlite3
gem 'sqlite3'
# systemd
gem 'systemd-daemon',
    github: 'acquia/systemd-daemon',
    ref: 'wip'
